### ISSUE TITLE
companyRep cannot access user

### ISSUE THREAD

**Issue by jonatan-kruse** [careerfairsystems/nexpo-backend-nova#51]
The call GET to
> ​/api​/users​/{id}

gives back 403 (forbidden) when a companyRep calls it.
This is because even though it looks like a companyRep have permission to use till GET-request this is ONLY if it has a companyConnection to the user

**Comment by UsperX** [comment]
As stated in pull request #52, is the problem that _await _applicationRepo.ApplicationExists(id, companyId)_  & _connectionRepo.ConnectionExists(id, companyId)_ are provided with a userId instead of a studentId when comparing against the content of the studentSessionApplications & companyConnestions.
